name: Build pdf

on: [push,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Compile .tex
        uses: ./build
        with:
          filename: 'src/cv.tex'

      - name: Commit compiled pdf files
        if: success()
        run: |
          git add -f **.pdf
          author=${GITHUB_ACTOR:=github-actions}
          git config user.name "$author"
          git config user.email "$author@users.noreply.github.com"
          git commit --allow-empty -m "✅ Actualize pdf"
          git push

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out # The folder the action should deploy.
